#[[plugins]]
#repo = 'hdima/python-syntax'
#on_ft = 'python'
#hook_add = 'let python_highlight_all = 1'

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = 'Shougo/deoplete.vim'
on_ft = 'python'
#requires jedi (install by 'pip install jedi')
#ここから有無をチェックしてインストールまでやりたい

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = 'let g:jedi#force_py_version = 3' 

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
#quickrun-hook 集

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
#syntaxcheck
on_ft = 'python'
depends = ['Shougo/vimproc', 'thinca/vim-quickrun', 'osyo-manga/shabadou.vim', 'cohama/vim-hier']
##自動インストール書きかけ
##hook_post_update = '''
##    "osyo-manga/vim-watchdogs", {
##      \"build": {
##        \"mac": ["pip3 install flake8"],
##        \"cygwin": ["pip3install flake8"],
##        \"linux": ["pip3 install flake8"]},
##'''
#hook_add = '''
#      let g:watchdogs_check_BufWritePost_enable = 1
#      let g:watchdogs_check_CursorHold_enable = 1
#      if !exists("g:quickrun_config")
#        let g:quickrun_config = {}
#      endif
#      let g:quickrun_config["watchdogs_checker/_"] = {
#      \ "outputter/quickfix/open_cmd" : "",
#      \ "runner/vimproc/updatetime" : 50,
#      \ "hook/qfsigns_update/enable_exit": 1,
#      \ "hook/qfsigns_update/priority_exit": 3,
#      \}
#      let s:flake8 = system('flake8 --version 2>/dev/null')
#      if s:flake8 != ""
#        let g:quickrun_config["python/watchdogs_checker"] = {
#        \ "type" : "watchdogs_checker/flake8"
#        \}
#      endif
#      call watchdogs#setup(g:quickrun_config)
#    '''
