[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
#Hook集

[[plugins]]
repo = 'thinca/vim-quickrun'
on_hook = '''
let g:quickrun_config = {
\   "_" : {
\       "hook/close_denite_quickfix/enable_hook_loaded" : 1,
\       "hook/denite_quickfix/enable_failure" : 1,
\       "hook/close_quickfix/enable_success" : 1,
\       "hook/close_buffer/enable_failure" : 1,
\       "hook/close_buffer/enable_empty_data" : 1,
\       "outputter" : "multi:buffer:quickfix",
\       "outputter/buffer/split" : ":botright 8sp",
\       "runner" : "vimproc",
\       "runner/vimproc/updatetime" : 60
\   },
\}
'''
#quickrun.vim 本体
# runner/vimproc/updatetime で出力バッファの更新間隔をミリ秒で設定できます
# updatetime が一時的に書き換えられてしまうので注意して下さい
#  "outputter/buffer/close_on_empty" : 
#エラーがない場合勝手に閉じる、quickrun側での設定
#denite or unite
#unite -> denite互換性あれば。
#quickrunのpython環境設定

#依存関係
#thinca/vim-quickrun
#    +osyo-manga/shabadou
#    |    +Shougo/unite(Shougo/denite.nvim)
#    |    +osyo-manga/unite-quickfix(compatibility??) <- 未導入
#    +Shougo/vimproc


[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
#requires jedi (install by 'pip install jedi')
#jedi, Neovim, neovim-python client
##ここから有無をチェックしてインストールまでやりたい

#[[plugins]]
#repo = 'kevinw/pyflakes-vim'
#on_ft = 'python'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'
#hook_add = 'let g:jedi#force_py_version = 3' 

[[plugins]]
repo = 'jceb/vim-hier'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
hook_add = '''
    if !exists("g:quickrun_config")
        let g:quickrun_config = {}
    endif
    let g:quickrun_config["watchdogs_checker/_"] = {
      \ "outputter/quickfix/open_cmd" : "",
      \ }
    let g:watchdogs_check_CursorHold_enable = 1
    let g:quickrun_config = {
    \   "python/watchdogs_checker" : {
    \       "type" : "watchdogs_checker/flake8",
    \   }
    \}
    '''
#    let g:quickrun_config = {
#    \   "python/watchdogs_checker" : {
#    \       "type" : "watchdogs_checker/flake8",
#    \   } <- これquickrunに書くべきなのか？？？
# ユーザ側で定義した g:quickrun_config
#let g:quickrun_config = { ... }
#前項参照ということで。
#
#
# この関数に g:quickrun_config を渡す
# この関数で g:quickrun_config にシンタックスチェックを行うための設定を追加する
# 関数を呼び出すタイミングはユーザの g:quickrun_config 設定後
