[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    '''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
hook_add = '''
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_hook = '''
let g:quickrun_config = {
\   "_" : {
\       "hook/close_denite_quickfix/enable_hook_loaded" : 1,
\       "hook/denite_quickfix/enable_failure" : 1,
\       "hook/close_quickfix/enable_success" : 1,
\       "hook/close_buffer/enable_failure" : 1,
\       "hook/close_buffer/enable_empty_data" : 1,
\       "outputter" : "multi:buffer:quickfix",
\       "outputter/buffer/split" : ":botright 8sp",
\       "runner" : "vimproc",
\       "runner/vimproc/updatetime" : 60
\   },
\}
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
#Hook集
#依存関係
#thinca/vim-quickrun
#    +osyo-manga/shabadou
#    |    +Shougo/unite(Shougo/denite.nvim)
#    |    +osyo-manga/unite-quickfix(compatibility??) <- 未導入
#    +Shougo/vimproc


[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = 'python'
#requires jedi (install by 'pip install jedi')
#jedi, Neovim, neovim-python client
##ここから有無をチェックしてインストールまでやりたい

#[[plugins]]
#repo = 'kevinw/pyflakes-vim'
#on_ft = 'python'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'
#hook_add = 'let g:jedi#force_py_version = 3' 

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', 'djangohtml']

#[[plugins]]
#repo = 'neomake/neomake'
#on_ft = ['python']
#hook_source = '''
#    autocmd! BufEnter,BufWritePost * Neomake
#    let g:neomake_python_enabled_makers = ['python', 'flake8']
#    augroup my_neomake_signs
#        au!
#        autocmd ColorScheme *
#            \ hi NeomakeErrorSign ctermfg=yellow |
#            \ hi NeomakeWarningSign ctermfg=red
#    augroup END
#'''

[[plugins]]
repo = 'w0rp/ale'
hook_source = '''
    "let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
    "call dein#add('itchyny/lightline.vim')
    "let g:lightline = {
    "  \'colorscheme': 'solarized'
    "  \'active': {
    "  \  'left': [
    "  \    ['mode', 'paste'],
    "  \    ['readonly', 'filename', 'modified'],
    "  \    ['ale'],
    "  \  ]
    "  \},
    "  \'component_function': {
    "  \  'ale': 'ALEStatus'
    "  \}
    "\ } 
    "
    "function! ALEStatus()
    "  return ALEGetStatusLine()
    "endfunction
    '''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'
# on_ft = ['python']

#[[plugins]]
#repo = 'jmcantrell/vim-virtualenv'
#on_ft = ['python']
#どちらか、有効化？
