[[plugins]]
repo = 'zchee/deoplete-jedi'
#requires jedi (install by 'pip install jedi')

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'hdima/python-syntax'
on_ft = 'python'
hook_add = 'let python_highlight_all = 1'
