[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    '''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
hook_add = '''
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_hook = '''
let g:quickrun_config = {
\   "_" : {
\       "runner" : "vimproc",
\       "runner/vimproc/updatetime" : 60,
\       "outputter" : "error",
\       "outputter/buffer/close_on_empty" : 1,
\       "outputter/buffer/split" : ":botright 8sp"
\   },
\}
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
if = "has('nvim')"
on_ft = 'python'
#requires jedi (install by 'pip install jedi')
#jedi, Neovim, neovim-python client
##ここから有無をチェックしてインストールまでやりたい

#[[plugins]]
#repo = 'kevinw/pyflakes-vim'
#on_ft = 'python'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

#[[plugins]]
#repo = 'lambdalisue/vim-django-support'
#on_ft = ['python', 'djangohtml']

#[[plugins]]
#repo = 'Vimjas/vim-python-pep8-indent'
#on_ft = ['python']

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'
# on_ft = ['python']

#[[plugins]]
#repo = 'jmcantrell/vim-virtualenv'
#on_ft = ['python']
#どちらか、有効化？
