[[plugins]]
repo = 'Shougo/denite.nvim'


[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
#requires jedi (install by 'pip install jedi')
#jedi, Neovim, neovim-python client
##ここから有無をチェックしてインストールまでやりたい

#[[plugins]]
#repo = 'kevinw/pyflakes-vim'
#on_ft = 'python'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'
#hook_add = 'let g:jedi#force_py_version = 3' 

[[plugins]]
repo = 'jceb/vim-hier'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = {
    \   "_" : {
    \       "hook/close_denite_quickfix/enable_hook_loaded" : 1,
    \       "hook/unite_quickfix/enable_failure" : 1,
    \       "hook/close_quickfix/enable_exit" : 1,
    \       "hook/close_buffer/enable_failure" : 1,
    \       "hook/close_buffer/enable_empty_data" : 1,
    \       "outputter" : "multi:buffer:quickfix",
    \       "hook/shabadoubi_touch_henshin/enable" : 1,
    \       "hook/shabadoubi_touch_henshin/wait" : 20,
    \       "outputter/buffer/split" : ":botright 8sp",
    \       "runner" : "vimproc",
    \       "runner/vimproc/updatetime" : 40,
    \   }
    \}
'''
#http://d.hatena.ne.jp/osyo-manga/20120919/1348054752

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
hook_add = '''
    " ユーザ側で定義した g:quickrun_config
    "let g:quickrun_config = { ... }
    "前項参照ということで。


    " この関数に g:quickrun_config を渡す
    " この関数で g:quickrun_config にシンタックスチェックを行うための設定を追加する
    " 関数を呼び出すタイミングはユーザの g:quickrun_config 設定後
    call watchdogs#setup(g:quickrun_config)
'''
