[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
    let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
    let g:ale_set_loclist = 0
    let g:ale_set_quickfix = 1
    
    '''

[[plugins]]
repo = 'delphinus/lightline-delphinus'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {'colorscheme': 'solarized'}
     '''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
" vim-indent-guides
" Vim 起動時 vim-indent-guides を自動起動
let g:indent_guides_enable_on_vim_startup=1
" Disable on help anda NerdTree
let g:indent_guides_exclude_filetypes = ['help', 'nerdtree']
" ガイドをスタートするインデントの量
let g:indent_guides_start_level=2
" 自動カラー無効
let g:indent_guides_auto_colors=0
" 奇数番目のインデントの色 -> solarized base02
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#073642 ctermbg=0
" 偶数番目のインデントの色 -> solarized base01
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#586e75 ctermbg=8
" ガイドの幅
"let g:indent_guides_guide_size = 4
'''

[[plugins]]
repo = 'Shougo/vimproc'
hook_post_update = '''
  if dein#util#_is_windows()
      let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
      let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
      let cmd = 'gmake'
  else
      let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''
##非同期処理をするために必要
##要ビルド

#[[plugins]]
#repo = 'jceb/vim-hier'
##ハイライトするやつ
#watchdogsから参照されていないため無効
